language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: deps=high
        - php: 7.1
          env: deps=low
    fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ ! $deps || $deps = high ]]; then composer install; else composer update --prefer-lowest --prefer-stable; fi

script:
  - ./vendor/bin/phpspec run --format=dot
  - ./vendor/bin/behat --format=progress

